version: '3.8'

services:
  # Node.js/Express server
  server:
    container_name: pk-server-pg
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    env_file:
      - ./server/.env.production.postgres

  # React/Vite.js client
  client:
    container_name: pk-client-pg
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
